# baseurl for personal page instead of a project page . Append this if a project.
baseurl: ""
url: https://williamdunstanmorris.github.io/

# website info
title: william morris
description: 'Developer && Devops working on EPSRC project for 3D Spatial Audio'
favicon: assets/img/favicon.png
image: assets/img-compressed
elogo: assets/img/email.png
glogo: assets/img/github.png
slogo: assets/img/soundcloud.png

# social info
navigation: true # show the navbar links
subscribers: true # you need to connect an external service for this to work.

author:
  name:           'William Morris'
github: https://github.com/williamdunstanmorris
email: william.dunstan.morris@gmail.com
instagram: https://www.instagram.com/its_dizzylo/
permalink: /:title:output_ext

# Code Highlighter
## 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge
highlight:
  line_number: true

#### Markdown Processors
## 'redcarpet' is unsupported on GitHub Pages now.
markdown: kramdown
kramdown:
    input: GFM

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

  # Disqus
disqus: False
disqus_shortname: jekyller # replace with your disqus username

# Google Analytics
google_analytics: UA-69281367-1 # replace with your GA tracking identifier

defaults:
  post:
    layout: navbar-post
    permalink: /:title:output_ext
    show-in-navbar: false
    fill: false
    title-colour: 'black'
    published: false
    class: nil
    categories: speak
    excerpt_separator: <!--more-->
    pdfdownload: null
    nav-archive: true
    category: work
