# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            William Morris
tagline:          'A Jekyll theme'
description:      'Developer && Devops working on EPSRC project for 3D Spatial Audio'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-gist
  - jekyll-paginate
